[package]
name = "backend"
version = "0.1.0"
authors = ["Cheng Lin <chlin@pdx.edu>"]
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
actix-rt = "2.8.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
rusqlite = "0.29.0"